from aiogram.types import InputFile

marmok_voice = [
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_а на ваше мнение.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_а х#ли я зигую.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_байонета.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_балкон на колесах.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_банзай.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_бобик.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_божечки-кошечки.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_бонжур тебе в е#ало.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_братан, могу объяснить.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_бухой алкаш.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_в чём смысл.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_вау, что за место.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_веришь у#бу.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_вперед бл#ть!.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_вращайте барабан.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_вы не жирные.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_вызовите копов.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_гори в аду, с#ка.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_дай по е#алу и я пойду.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_дайте по#рать.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_дебил с гранатой.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_дебилизм.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_довыпендривался.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_дро#ишь с#ка, да.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_е#альник в раскладушку.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_е#аный экибастуз.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_женщина, не пейте воду.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_женщины, быстрее.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_завали е#ало.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_закрой свою пасть.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_захватим весь майнкрафт.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_здарова, сп#рмобак.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_здрасте.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_зубов бояться.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_и да, я в трусах.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_извините, что прерываю.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_изыди.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_имбицил смердячий.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_кайфую.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_как говорил конфуций.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_как же это тупо.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_как сложно жирным.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_как тут устоять.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_как ты дожил.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_какая загадочная ху#ня.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_какого лешего.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_карась волосатый.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_каркнешь еще раз.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_кто такой креативный.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_кто там каркает.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_купил авп.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_майнкрафт.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_мама зря стонала.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_мама, вызывай ментов.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_микки маус.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_мистер, у вас кариес.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_может через постель.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_мозги это не твое.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_не понял.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_не стреляйте.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_невидимый.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_ни#ера себе.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_нырни.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_о, да!.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_огонь не игрушка.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_отдыхай.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_откуда.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_отпустите меня.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_палево, палево.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_палочка волшебная.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_папа зря потел.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_пахнет.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_перепутал его лицо.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_пи#арюга мелкая.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_потерял нить.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_потому что я бэтмэн.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_пошли на б.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_приготовьте свои мешки.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_просто завтыкал.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_пусто, как в попе.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_раз, два, три.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_разнесу твою будку.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_растворись, у#ба.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_рожденный бегать.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_рпг через плечо.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_рюмка водки на столе.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_с вас 2039 баксов.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_са#бись.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_сделаю мини подушку.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_сегодня среда.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_сексуальный медведь.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_скилл приди.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_слушай, шампиньон.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_снимайте панталоны.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_сосите писос.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_сырные дырочки.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_сюда, челядь.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_тебе ж#па.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_тебе повезло.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_тебя сделал человек.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_ти кто такой.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_тут у нас тихий час.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_ты готов к школьной столовке.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_ты дебил тот еще.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_ты же в церкви.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_ты зае#ал каркать.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_ты из военкома.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_ты издеваешься.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_ты не против.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_ты официально послан.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_ты прав.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_ты сигналы попутал.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_ты тонешь.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_ты че мне настроение портишь.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_ты че призрак.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_ты че простыл.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_ты че э#анутый.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_у него ключ.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_у тебя что-то в ж#пе дергается.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_убей меня.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_уииииии.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_уровень интеллекта.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_уронил в тазик.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_успокой свои нервы.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_ухуу.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_фууу.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_х#ли кровоточишь.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_х#як!.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_хвост трубой, грудак горой.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_хорошей дороги.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_хочешь ногой по е#алу.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_читер е#аный.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_что за проблемы.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_что за хе#ня!.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_что это за ху#ня.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_что это.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_шаловливое настроение.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_шо ты за ху#ня.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_эй, чебурек.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_это было потно.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_я вас ненавижу.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_я ворую бахилы.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_я иду на#ер.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_я каратэ знаю.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_я на х#ю у зевса.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_я обиделся.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_я похож на ветеринара.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_я ребенок из девяностых.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_я рыжий пес.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_я съ#бываю.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_я тя щас расх#ярю.ogg"),
InputFile("C:\\Users\\choco\\Downloads\\parsing\\voice\\мармок\\мармок_я художник.ogg"),

]